version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./app.env
    ports:
      - '8800:8000'
    volumes:
      - mysqlDB:/var/lib/mysql
volumes:
  mysqlDB:
